namespace final_project.Models;

public class Recipe {
    public int UserId;
    public int idMeal; 
    public string strMeal = ""; 
    public string strCategory = ""; 
    public string strArea = ""; 
    public string strInstructions = ""; 
    public string strMealThumb = ""; 
    public string strTags = ""; 
    public string strYoutube = ""; 
    public string strIngredients1 = ""; 
    public string strIngredients2 = ""; 
    public string strIngredients3 = ""; 
    public string strIngredients4 = ""; 
    public string strIngredients5 = ""; 
    public string strIngredients6 = ""; 
    public string strIngredients7 = ""; 
    public string strIngredients8 = ""; 
    public string strIngredients9 = ""; 
    public string strIngredients10 = ""; 
    public string strIngredients11 = ""; 
    public string strIngredients12 = ""; 
    public string strIngredients13 = ""; 
    public string strIngredients14 = ""; 
    public string strIngredients15 = ""; 
    public string strIngredients16 = ""; 
    public string strIngredients17 = ""; 
    public string strIngredients18 = ""; 
    public string strIngredients19 = ""; 
    public string strIngredients20 = ""; 
    public string strMeasure1 = ""; 
    public string strMeasure2 = ""; 
    public string strMeasure3 = ""; 
    public string strMeasure4 = ""; 
    public string strMeasure5 = ""; 
    public string strMeasure6 = ""; 
    public string strMeasure7 = ""; 
    public string strMeasure8 = ""; 
    public string strMeasure9 = ""; 
    public string strMeasure10 = ""; 
    public string strMeasure11 = ""; 
    public string strMeasure12 = ""; 
    public string strMeasure13 = ""; 
    public string strMeasure14 = ""; 
    public string strMeasure15 = ""; 
    public string strMeasure16 = ""; 
    public string strMeasure17 = ""; 
    public string strMeasure18 = ""; 
    public string strMeasure19 = ""; 
    public string strMeasure20 = ""; 
}